spring.application.name=springAlura
spring.jackson.mapper.accept-case-insensitive-properties=true

# Conecta no banco oficial 'postgres' e entra direto na pasta do seu schema
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=spring_alura
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

