# Nome do projeto e codificação de texto
spring.application.name=springAlura
spring.messages.encoding=UTF-8
# Dados de conexão do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=spring_alura&charSet=UTF-8
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# Configurações do Hibernate (Recria tabelas e formata o SQL no console)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Ignora maiúsculas/minúsculas nas chaves do JSON recebido
spring.jackson.mapper.accept-case-insensitive-properties=true
# Configurações visuais e de filtros do Swagger UI
springdoc.api-docs.enabled=true
springdoc.paths-to-exclude=/error, /api/profile**, /api/profile/**
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.docExpansion=none
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.displayRequestDuration=true
# Logs do Spring Security e a chave secreta do Token JWT
logging.level.org.springframework.security=DEBUG
api.security.token.secret=secret
# Auditoria do Envers (Sufixo das tabelas e nomes das colunas de revisão)
spring.jpa.properties.org.hibernate.envers.global_with_modified_flags=true
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_auditoria
spring.jpa.properties.org.hibernate.envers.revision_field_name=REVISION_ID
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=REVISION_TYPE
